### ISSUE TITLE
[IOS] Black Screen with error about metal.

### ISSUE THREAD

**Issue by Archi97** [zappar-xr/universal-ar-unity#10]
**Describe the bug**
When running app with Zap Camera. im seeing error log like this " cant find device with metal support".
and the screen is black. 
Interesting thing is, face can be recognized, but camera not rendering on the screen. 

i havn't commented the line from zappar-lib.h,  and have added OpenGles.framework (actually it is added automatically.)
Need quick help. If you have Discord please share it.

**Smartphone (please complete the following information):**
 - Device: Iphone all versions
 - OS: 13+,14+,15+
 - Version Zappar version 3.0.1

**Comment by nfynt-zap** [comment]
Does the following forum post help? 
https://forum.zap.works/t/ios-no-valid-metal-device/9148

**Comment by Archi97** [comment]
Nope

**Comment by Archi97** [comment]
@nfynt-zap  please check the images in the forum

**Comment by Archi97** [comment]
@nfynt-zap  new update. problem seems to come from Vuforia 9.8.8
Please check forum

**Comment by nfynt-zap** [comment]
@Archi97 
We won't be able to fix any issues with Vuforia or check for compatibility with it. Thus I suggest you give it a try on your own or reach out to Vuforia support team for help.

I'll mark this issue closed. You're welcome to submit new issues or suggestion that might be helpful for the community.

**Comment by Archi97** [comment]
What you mean. Your SDK not working with other SDK and not theirs. You should investigate it and solve. 
Also, what about Darker camera?

**Comment by nfynt-zap** [comment]
You comment mentions that the `problem seems to come from Vuforia`, so I am not sure what we can do about it.
Without any repro setup/project or specific details about the conflict we don't have much to investigate here.

Re dark camera, it seems like it could be due to `Linear` Color space. You may wanna change that to `Gamma` from editor settings and see if that helps. Also, another point to note would be: the default camera app does several post processing over default camera feed, such as - HDR, tonemapping, auto-focus, etc. So slight variation is to be expected. Though, currently it's much darker and I would start with editor and texture format settings.

**Comment by Archi97** [comment]
To investigate,  Install Vuforia 9.8.8 and Zappar 3.0.1
Yes problem comes when Vuforia is in project.  the it is working great, but zappar didn't, so i guess you should investigate, find issue, and solve that case of bug with conflict. 

About Darker camera, im using Gamme,  and about native camera - i dont know what are they doing, but the look of it and the look of ARFoundation, Vuforia and Unity's native camera are same.

**Comment by Archi97** [comment]
Hello Everyone who is watching this thread. 
I found issue and fixed it. Will do pull request @nfynt-zap .
