### ISSUE TITLE
[WebGL][iOS]UniversalAR is not working

### ISSUE THREAD

**Issue by tng2903** [zappar-xr/universal-ar-unity#4]
**Describe the bug**
When viewing on Android, the build work correctly, but viewing on iOS only result in the loading animation, nothing more

**To Reproduce**
1. Used UAR version '1.2.0' + Samples
2. With Unity version '2020.3.11f' without SRP and build platform as 'WebGL'
3. Build with only sample scene FaceTracker.unity
4. View on Safari/Chrome on iOS 12.0

**Expected behavior**
The project can be loaded

**Smartphone (please complete the following information):**
 - Device: [iPad 2019]
 - OS: [iOS 12.0]
 - Browser [Safari, Chrome]
 - Version [89]

**Additional context**
The build has been uploaded on an SSL-enabled hosting and work correctly on Android, the problem only happens on iOS

**Comment by tng2903** [comment]
I've also test on latest 1.2.0 version of UniversalAR without any success

**Comment by francesca-may** [comment]
Hi there,

Thank you so much for logging this issue. I performed some testing today using the 1.2.0 version of the Universal AR SDK and an iPad which uses iOS 12.0; and could not replicate the issue.

Could there be any more additional information that you could provide? For example, do you have any debug or error logs that you could share with us? How are you attempting to serve/host your project in order to run it? Does using the '`Upgrade Project Settings to Publish`' Zappar menu item assist here at all?

It would also be very helpful if you were able to share a stripped down version of your project with us.

**Comment by tng2903** [comment]
Hello, I've uploaded the test project here for reference purpose https://github.com/tng2903/zappar-universal-testcase.git

This project is created by these steps:
- Create new project with Unity 2020
- Add Zappar plugin by modifying package manifest file
- Import Samples from Zappar
- Add in some model and scripts into sample scene InstantTracking
- Use the "Upgrade Project Setting" menu
- Build and Export to WebGL
- Test on iOS safari

If your test project can work without problem, can you share it for reference purpose @francesca-may ?

**Comment by tng2903** [comment]
Hello, is there any update for this issue? @francesca-may

**Comment by francesca-may** [comment]
Hi there,

I was able to run your test project without error.

I have emailed a more detailed response to your support ticket with my test project.

For reference, it also seems that another user reported a similar issue to this. They found that `requesting the mobile site for Safari` fixed their particular issue.

**Comment by tng2903** [comment]
The test project is working on Safari iOS? It's weird that it's not working on my end. Can I ask what version of Unity was used to test with that project?
I will try requesting mobile site and report the result then.

**Comment by tng2903** [comment]
Hello @francesca-may , I've tried the updated test project but the problem still persist, it's only shown a loading indicator and nothing else, even after waiting for 5 minutes

**Comment by nfynt-zap** [comment]
Hi @tng2903 ,

thanks for bringing this issue to our attention. We have identified the issue and it seems that the Safari on iPad tries to request a MacOS site which is weird. Anyways please find the patch fix for this as a new WebGLTemplates folder in the attachment. 

You'll need to replace the existing WebGLTemplates folder located inside `com.zappar.uar@xxxxx` (project/dir/Library/PackageCache/) with this new Templates. Please note that directly replacing this within Assets is not reliable since it's updated every time Unity is reloaded.

Let us know how you get on, or have any other issues.

Cheers,

[WebGLTemplates.zip](https://github.com/zappar-xr/universal-ar-unity/files/7250499/WebGLTemplates.zip)
