### ISSUE TITLE
[WebGL][iOS]UniversalAR is not working (not enough memory?)

### ISSUE THREAD

**Issue by tng2903** [zappar-xr/universal-ar-unity#5]
Describe the bug
When viewing on Android, the build work correctly, but viewing on iOS only result in the loading animation, nothing more

To Reproduce

Used UAR version '1.2.0' + Samples
**_Build to WebGL, since WebGL2.0 is not working on iOS_**
With Unity version '2020.3.11f' without SRP and build platform as 'WebGL'
Build with only sample scene InstantTracking.unity
View on Safari/Chrome on iOS 12.0
Expected behavior
The project can be loaded

Smartphone (please complete the following information):

Device: [iPad 2019]
OS: [iOS 12.0]
Browser [Safari, Chrome]
Version [89]
Additional context
The build has been uploaded on an SSL-enabled hosting and work correctly on Android, the problem only happens on iOS

Here are the screenshot of those error
![photo_2021-10-05_17-05-02](https://user-images.githubusercontent.com/1988874/136003463-0c9c310e-4727-4046-8f50-ac4e36081fcf.jpg)
![photo_2021-10-05_17-04-57](https://user-images.githubusercontent.com/1988874/136003473-daf5c1a8-6ae2-4b4d-8908-0bbecd73a1eb.jpg)

**Comment by nfynt-zap** [comment]
Hi @tng2903,

I think the error logs is quite clear and the application failed to load due to running out of executable memory. From Unitys' point of view I would suggest going through following article: https://blog.unity.com/technology/understanding-memory-in-unity-webgl in order the better understand the memory and GC differences for WebGL application.

That said, if you're just simply building sample scenes (which is pretty lite), you shouldn't have to worry about it yet. Can you make sure there are no other processes/tabs running on the device which may effect that.

Lastly, if you're only running the sample scenes and there are no other process eating up your available memory, then only thing I can think of is updating to newer version of iOS. We had tested the SDK on iOS version 14 across devices and browsers and didn't encounter this issue!

Best,

Edit: 
Feel free to extend this thread if the issue still persists and you're sure it's from the SDK! and you can build and run a simple WebGL build on iOS otherwise. In which case please share a minimum project with Unity player logs so we can further reproduce and investigate this.
