### ISSUE TITLE
Manual install option

### ISSUE THREAD

**Issue by xm007** [zappar-xr/universal-ar-unity#8]
Use suggest method to install SDK will stuck at "Please wait,installing a GIT package...".Use alt method will pop out a window "OpenSSL SSL_read:Connection was reset,errno 10054".So a manual install option is possible?
![OpenSSLfailed](https://user-images.githubusercontent.com/7972541/149874247-46af33b9-7e8e-44cf-8c53-bf7e38a9f928.png)
![waitinstall](https://user-images.githubusercontent.com/7972541/149874569-995085a2-fa5e-47ab-a298-89fc1a2ed2f7.png)

**Comment by nfynt-zap** [comment]
Hello @xm007,

The SSL error 10054 is likely due to your network firewall or git configuration... which failed in cloning the git repo after successfully establishing TLS connection with github.com.

Can you try substituting the https url with a ssh one. For example you can update your `manifest.json` as follows:

```
"dependencies": {
    "com.zappar.uar": "ssh://git@github.com/zappar-xr/universal-ar-unity.git"
  }
```

or you can try directly using this `ssh://git@github.com/zappar-xr/universal-ar-unity.git` from Package Manager within Unity editor as git package URL.

**Comment by xm007** [comment]
> 

Yes the SSH url is working(although the download speed is incredibly slow).But before use this url the Git need to be configured and also create a SSH Key for my own github account(somthing need to be metioned on readme).THX anyway!
